### ISSUE TITLE
Avast detects virus falsly

### ISSUE THREAD

**Issue by sagik-cf** [Ounzy/OpenBl#2]
Just downloaded the app through F-Droid and after I opened it Avast showed me this message

![Screenshot_20230306-234748_Avast Mobile Security](https://user-images.githubusercontent.com/76676453/223273990-62797165-a62f-492b-9519-76cdf8c00266.jpg)

This didn't make sense to me, since the app is open source so I just wanted to let you know about this.

**Comment by Ounzy** [comment]
Okay, thank you for telling me.

Just delete Avast for solving your problem😉.

No, to be honest I've no idea why Avast detects OpenBl as a virus.
The App gets the data from Api OpenLigaDB and works with it. Shouldn't be a virus in my opinion.
